#!/bin/bash -e
##############################################################
# Bam Annotations
# 
WALLTIME_BAMANN=5:00:00
MEMORY_BAMANN=32
CPU_BAMANN=1
NODES_BAMANN="nodes=1:ppn=1"
INPUT_BAMANN=$TASKBWA
MODULE_BAMANN="${NG_BEDTOOLS}"
PATH_BAMANN=

