#!/bin/bash -e
##############################################################
# Create bigwigs from bam files
# http://genome.ucsc.edu/util.html/
WALLTIME_BIGWIG=12:00:00
MEMORY_BIGWIG=12
CPU_BIGWIG=2
NODES_BIGWIG="nodes=1:ppn=2"
INPUT_BIGWIG=$TASKBOWTIE
MODULE_BIGWIG="${NG_UCSCTOOLS} ${NG_JAVA} ${NG_SAMTOOLS} ${NG_BEDTOOLS}"
PATH_BIGWIG=

