#!/bin/bash
##############################################################
# ChIP QC with CHANCE
# https://github.com/songlab/chance/downloads
TASK_CHANCE="chance"
WALLTIME_CHANCE=4:00:00
MEMORY_CHANCE=20
CPU_CHANCE=1
NODES_CHANCE="nodes=1:ppn=1"
INPUT_CHANCE=$TASK_BOWTIE
MODULE_CHANCE="${NG_CHANCE} ${NG_JAVA} ${NG_MATLAB} ${NG_R}"
PATH_CHANCE=

