#!/bin/bash -e
##############################################################
# Trim adapter with CUTADAPT ()
# https://code.google.com/p/cutadapt/
TASK_CUTADAPT="cutadapt"
WALLTIME_CUTADAPT=4:00:00
MEMORY_CUTADAPT=40
CPU_CUTADAPT=1
NODES_CUTADAPT="nodes=1:ppn=1"
INPUT_CUTADAPT="fastq"
MODULE_CUTADAPT="${NG_CUTADAPT}"
PATH_CUTADAPT=

