#!/bin/bash -e
##############################################################
# HOMER HIC 
# http://biowhat.ucsd.edu/homer/index.html
WALLTIME_HOMERHIC=60:00:00
MEMORY_HOMERHIC=60
CPU_HOMERHIC=8
NODES_HOMERHIC="nodes=1:ppn=8"
INPUT_HOMERHIC=$TASKBWA
MODULE_HOMERHIC="${NG_PERL} ${NG_HOMER}"
PATH_HOMERHIC=

