#!/bin/bash -e
##############################################################
# MEMECHIP
# http://meme.nbcr.net/
WALLTIME_MEMECHIP=48:00:00
MEMORY_MEMECHIP=40
CPU_MEMECHIP=8
NODES_MEMECHIP="nodes=1:ppn=8"
INPUT_MEMECHIP=$TASKMACS2
MODULE_MEMECHIP="${NG_BEDTOOLS} ${NG_PERL} ${NG_MEME}"
PATH_MEMECHIP=

MEMECHIPDATABASES=

