#!/bin/bash  -e
##############################################################
# Peakranger
# http://ranger.sourceforge.net/
WALLTIME_PEAKRANGER=12:00:00
MEMORY_PEAKRANGER=20
CPU_PEAKRANGER=1
NODES_PEAKRANGER="nodes=1:ppn=1"
INPUT_PEAKRANGER=$TASKBOWTIE
MODULE_PEAKRANGER="${NG_BOOST} ${NG_R} ${NG_PEAKRANGER}"
PATH_PEAKRANGER=

