#!/bin/bash -e
##############################################################
# reduced representation bisulfite sequencing mapping 
# https://code.google.com/p/bsmap/
WALLTIME_RRBSMAP=60:00:00
MEMORY_RRBSMAP=50
CPU_RRBSMAP=32
NODES_RRBSMAP="nodes=4:ppn=8"
INPUT_RRBSMAP="fastq"
MODULE_RRBSMAP="${NG_RRBSMAP}"
PATH_RRBSMAP=
