#!/bin/bash -e
##############################################################
# Wiggler
# https://sites.google.com/site/anshulkundaje/projects/wiggler
WALLTIME_WIGGLER=10:00:00
MEMORY_WIGGLER=60
CPU_WIGGLER=1
NODES_WIGGLER="nodes=1:ppn=1"
INPUT_WIGGLER=$TASKBWA
MODULE_WIGGLER="${NG_SAMTOOLS} ${NG_MATLAB} ${NG_WIGGLER}"
PATH_WIGGLER=

WIGGLER_UMAPDIR=
