#!/bin/sh -e

################################################################################
#   Blue
#
# IN : $SOURCE/fastq/$dir/*read1.fastq
# OUT: $OUT/$dir_healed/*.
################################################################################

if [ -n "$RUNBLUE" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # check if resources are properly defined
        if [ -z "$TASK_BLUE" ] || [ -z "$NODES_BLUE" ] || [ -z "$CPU_BLUE" ] || [ -z "$MEMORY_BLUE" ] || [ -z "$WALLTIME_BLUE" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
        
        $QSUB $ARMED $NGSANE_WAITFORJOB -k $CONFIG -t $TASK_BLUE -i $INPUT_BLUE -e $READONE.$FASTQ \
            -n $NODES_BLUE -c $CPU_BLUE -m $MEMORY_BLUE"G" -w $WALLTIME_BLUE \
            --command "${NGSANE_BASE}/mods/blue.sh -k $CONFIG -f <FILE> -o $INPUT_BLUE/<DIR>"_"$TASK_BLUE/" 

    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then

        # start a new section for a mod
        NGSANE_REPORT_HEADER "Blue" "$TASK_BLUE" "blue.sh"

        NGSANE_REPORT_TABLE "$TASK_BLUE" \
            "$INPUT_BLUE/<DIR>"_"$TASK_BLUE/" \
            ".stats.txt"                    \
            "PATTERN:Total reads:sed -n 2p | cut -d' ' -f 1" \
            "PATTERN:Reads OK:sed -n 3p | cut -d' ' -f 1" \
            "CALCULATE:Reads OK%:#3*100/#2" \
            "PATTERN:Healed:sed -n 7p | cut -d' ' -f 1" \
            "CALCULATE:Healed%:#5*100/#2" \
            "PATTERN:Not healed:sed -n 12p | cut -d' ' -f 1" \
            "CALCULATE:Not healed%:#7*100/#2" \
            "PATTERN:Discarded:sed -n 18p | cut -d' ' -f 1" \
            "CALCULATE:Discarded%:#9*100/#2" \
            "PATTERN:Subs:sed -n 21p | cut -d' ' -f 1" \
            "PATTERN:Dels:sed -n 22p | cut -d' ' -f 1" \
            "PATTERN:Ins:sed -n 23p | cut -d' ' -f 1"

        # finish the section
        NGSANE_REPORT_FOOTER  
  
    fi
fi	

	