#!/bin/bash -e

################################################################################
#  Mapping with bowtie v2
#
# IN:  $SOURCE/$dir/fastq/*read1.fastq
# OUT: $OUT/$dir/bowtie2/*$ASD.bam
################################################################################
if [ -n "$RUNBOWTIE2" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    if [ -z "$TASK_BOWTIE2" ] || [ -z "$NODES_BOWTIE2" ] || [ -z "$CPU_BOWTIE2" ] || [ -z "$MEMORY_BOWTIE2" ] || [ -z "$WALLTIME_BOWTIE2" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
    
    if [ ! -f ${FASTA%.*}.1.bt2 ];then
        # submit job for index generation if necessary
        INDEXJOBIDS=$(
            $QSUB $ARMED $NGSANE_WAITFORJOB -k $CONFIG -t $TASK_BOWTIE2 -i $INPUT_BOWTIE2 -e $READONE.$FASTQ \
            -n $NODES_BOWTIE2 -c $CPU_BOWTIE2 -m $MEMORY_BOWTIE2"G" \
            -w $WALLTIME_BOWTIE2 --commontask indexGenome \
            --command "${NGSANE_BASE}/mods/bowtie2Index.sh -k $CONFIG"
        ) && echo -e "$INDEXJOBIDS"
        INDEXJOBIDS=$(waitForJobIds "$INDEXJOBIDS")
    else
        INDEXJOBIDS=$NGSANE_WAITFORJOB 
    fi
    
    $QSUB $ARMED -k $CONFIG -t $TASK_BOWTIE2 -i $INPUT_BOWTIE2 -e $READONE.$FASTQ -n $NODES_BOWTIE2 -c $CPU_BOWTIE2 -m $MEMORY_BOWTIE2"G" -w $WALLTIME_BOWTIE2 $INDEXJOBIDS \
	       --command "${NGSANE_BASE}/mods/bowtie2.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_BOWTIE2 --rgsi <DIR>"
      
fi