#!/bin/bash -e

################################################################################
#   Mapping using BWA
#
# IN : $SOURCE/$dir/fastq/*read1.fastq
# OUT: $OUT/$dir/bwa/*$ASD.bam
################################################################################

if [ -n "$RUNBWA" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # check if resources are properly defined
        if [ -z "$TASK_BWA" ] || [ -z "$NODES_BWA" ] || [ -z "$CPU_BWA" ] || [ -z "$MEMORY_BWA" ] || [ -z "$WALLTIME_BWA" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
    
        if [ ! -f $FASTA.bwt ];then
            # submit job for index generation if necessary
            JOBIDS=$(
                $QSUB $ARMED $NGSANE_WAITFORJOB -k $CONFIG -t $TASK_BWA -i $INPUT_BWA -e $READONE.$FASTQ \
                -n $NODES_BWA -c $CPU_BWA -m $MEMORY_BWA"G" \
                -w $WALLTIME_BWA --commontask indexGenome \
                --command "${NGSANE_BASE}/mods/bwaIndex.sh -k $CONFIG"
            ) && echo -e "$JOBIDS"
            JOBIDS=$(waitForJobIds "$JOBIDS")
        else
            JOBIDS=$NGSANE_WAITFORJOB
        fi
    
        $QSUB $ARMED -k $CONFIG -t $TASK_BWA -i $INPUT_BWA -e $READONE.$FASTQ \
            -n $NODES_BWA -c $CPU_BWA -m $MEMORY_BWA"G" -w $WALLTIME_BWA $JOBIDS \
            --command "${NGSANE_BASE}/mods/bwa.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_BWA --rgsi <DIR>"

    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then

        NGSANE_REPORT_HEADER "BWA" "$TASK_BWA" "bwa.sh" "$ASD.bam"

        NGSANE_REPORT_TABLE "$TASK_BWA" \
            "$OUT/<DIR>/$TASK_BWA"  \
            "$ASD.bam.stats" \
            "LINK:<SAMPLE>$ASD.bam.html" \
            "PATTERN:Total reads::sed -n 1p | cut -d' ' -f 1" \
            "PATTERN:Qfail::sed -n 1p | cut -d' ' -f 3" \
            "PATTERN:Duplicates::sed -n 2p | cut -d' ' -f 1" \
            "CALCULATE:Duplicates %:80:#4*100/#2" \
            "PATTERN:Mapped::sed -n 3p | cut -d' ' -f 1" \
            "CALCULATE:Mapped %:70:#6*100/#2" \
            "PATTERN:Mapped pairs::sed -n 7p | cut -d' ' -f 1 | xargs echo 0.5* | bc " \
            "CALCULATE:Mapped pairs %:70:#8*2*100/#2" \
            "PATTERN:Singletons::sed -n 9p | cut -d' ' -f 1" 
        
        NGSANE_REPORT_FOOTER 
        
    fi
fi
