#!/bin/bash -e

################################################################################
#  ChIP-seq QC with CHANCE
#
# IN: $SOURCE/$dir/bowtie/*.bam
# OUT: $OUT/$dir/chance/
################################################################################
if [ -n "$RUNCHANCE" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    if [ -z "$TASK_CHANCE" ] || [ -z "$NODES_CHANCE" ] || [ -z "$CPU_CHANCE" ] || [ -z "$MEMORY_CHANCE" ] || [ -z "$WALLTIME_CHANCE" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi

    $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_CHANCE -i $INPUT_CHANCE -e $ASD.bam \
        -n $NODES_CHANCE -c $CPU_CHANCE -m $MEMORY_CHANCE"G" -w $WALLTIME_CHANCE \
        --command "${NGSANE_BASE}/mods/chance.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_CHANCE"
fi
