#!/bin/bash -e

################################################################################
#   CUTADAPT remove contaminants
#
# IN : $SOURCE/fastq/$dir/*read1.fastq
# OUT: $SOURCE/fastq/$dir_cutadapt/*read1.fastq
################################################################################

if [ -n "$RUNCUTADAPT" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # check if resources are properly defined
        if [ -z "$TASK_CUTADAPT" ] || [ -z "$NODES_CUTADAPT" ] || [ -z "$CPU_CUTADAPT" ] || [ -z "$MEMORY_CUTADAPT" ] || [ -z "$WALLTIME_CUTADAPT" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
        
        $QSUB $ARMED $NGSANE_WAITFORJOB -d -k $CONFIG -t $TASK_CUTADAPT -i $INPUT_CUTADAPT -e $READONE.$FASTQ \
            -n $NODES_CUTADAPT -c $CPU_CUTADAPT -m $MEMORY_CUTADAPT"G" -w $WALLTIME_CUTADAPT \
            --command "${NGSANE_BASE}/mods/cutadapt.sh -k $CONFIG -f <FILE>" 
    
    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
    
        NGSANE_REPORT_HEADER "Cutadapt" "$TASK_CUTADAPT" "cutadapt.sh"

        NGSANE_REPORT_TABLE "$TASK_CUTADAPT" \
            "$OUT/fastq/<DIR>_$TASK_CUTADAPT"  \
            ".stats" \
            "PATTERN:Reads::fgrep -w 'Processed reads' | head -n 1 | cut -d' ' -f 3" \
            "PATTERN:Trimmed::fgrep -w 'Trimmed reads' | head -n 1 | cut -d' ' -f 3" \
            "CALCULATE:%:80:#3*100/#2" \
            "PATTERN:Filtered short reads::fgrep -w 'Too short reads' | head -n 1 | cut -d' ' -f 4" \
            "CALCULATE:%:80:#5*100/#2" \
            "PATTERN:Filtered long reads::fgrep -w 'Too long reads' | head -n 1 | cut -d' ' -f 4" \
            "CALCULATE:%:80:#7*100/#2" \
            "PATTERN:Remaining::fgrep -w 'remaining reads' | head -n 1 | cut -d' ' -f 3" \
            "CALCULATE:%:80:#9*100/#2"

        NGSANE_REPORT_FOOTER   
  
    fi
fi	

	