#!/bin/bash -e

################################################################################
#   CUTADAPT remove contaminants
#
# IN : $SOURCE/fastq/$dir/*read1.fastq
# OUT: $SOURCE/fastq/$dir_cutadapt/*read1.fastq
################################################################################

if [ -n "$RUNCUTADAPT" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # check if resources are properly defined
        if [ -z "$TASK_CUTADAPT" ] || [ -z "$NODES_CUTADAPT" ] || [ -z "$CPU_CUTADAPT" ] || [ -z "$MEMORY_CUTADAPT" ] || [ -z "$WALLTIME_CUTADAPT" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
        
        $QSUB $ARMED $NGSANE_WAITFORJOB -d -k $CONFIG -t $TASK_CUTADAPT -i $INPUT_CUTADAPT -e $READONE.$FASTQ \
            -n $NODES_CUTADAPT -c $CPU_CUTADAPT -m $MEMORY_CUTADAPT"G" -w $WALLTIME_CUTADAPT \
            --command "${NGSANE_BASE}/mods/cutadapt.sh -k $CONFIG -f <FILE>" 
    
    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
    
        # start a new section for a mod
        NGSANE_REPORT_HEADER "Cutadapt" "$TASK_CUTADAPT" "cutadapt.sh"

        echo "[NOTE] the cutadapt.sh mod does not provide a report"

        # finish the section
        NGSANE_REPORT_FOOTER   
  
    fi
fi	

	