#!/bin/sh -e

################################################################################
#   FastQC summary of fastq files
#
# IN : $SOURCE/fastq/$dir/*read1.fastq
# OUT: $OUT/$dir/fastQC/*
################################################################################
if [ -n "$RUNFASTQC" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # check if resources are properly defined
        if [ -z "$TASK_FASTQC" ] || [ -z "$NODES_FASTQC" ] || [ -z "$CPU_FASTQC" ] || [ -z "$MEMORY_FASTQC" ] || [ -z "$WALLTIME_FASTQC" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
        
        $QSUB $ARMED $NGSANE_WAITFORJOB -d -k $CONFIG -t $TASK_FASTQC -i $INPUT_FASTQC -e $READONE.$FASTQ \
            -n $NODES_FASTQC -c $CPU_FASTQC -m $MEMORY_FASTQC"G" -w $WALLTIME_FASTQC \
        	--command "${NGSANE_BASE}/mods/fastQC.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_FASTQC" 

    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
    
        NGSANE_REPORT_HEADER "FastQC" "$TASK_FASTQC" "fastQC.sh"

        NGSANE_REPORT_TABLE "$TASK_FASTQC" \
            "$OUT/<DIR>/$TASK_FASTQC"  \
            ".txt" \
            "LINK:<SAMPLE>.html" \
            "FIGURE::20:<SAMPLE>/Icons/tick.png:15:0" \
            "PATTERN::20:grep '>>.*pass' | wc -l" \
            "FIGURE::20:<SAMPLE>/Icons/warning.png:15:0" \
            "PATTERN::20:grep '>>.*warn' | wc -l" \
            "FIGURE::20:<SAMPLE>/Icons/error.png:15:0" \
            "PATTERN::20:grep '>>.*fail' | wc -l" \
            "PATTERN:Encoding::grep 'Encoding' | head -n 1 | cut -f 2" \
            "PATTERN:Library size::grep 'Total Sequences' | head -n 1 | cut -f 2" \
            "PATTERN:Length:80:grep 'Sequence length' | head -n 1 | cut -f 2" \
            "PATTERN:%GC:40:grep '%GC' | head -n 1 | cut -f 2" \
            "FIGURE::90:<SAMPLE>/Images/per_base_quality.png:60:1" \
            "FIGURE::90:<SAMPLE>/Images/duplication_levels.png:60:1" \
            "FIGURE::90:<SAMPLE>/Images/per_sequence_gc_content.png:60:1" \
            "FIGURE::90:<SAMPLE>/Images/per_base_sequence_content.png:60:1" 
        
        NGSANE_REPORT_FOOTER   
  
    fi
fi	

	
