#!/bin/sh -e 

################################################################################
#   FASTQSCREEN 
#
# IN : $SOURCE/fastq/$dir/*read1.fastq
# OUT: $OUT/$dir/fastqscreen/*.
################################################################################

if [ -n "$RUNFASTQSCREEN" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # check if resources are properly defined
        if [ -z "$TASK_FASTQSCREEN" ] || [ -z "$NODES_FASTQSCREEN" ] || [ -z "$CPU_FASTQSCREEN" ] || [ -z "$MEMORY_FASTQSCREEN" ] || [ -z "$WALLTIME_FASTQSCREEN" ]; then 
            echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; 
        fi
        
        $QSUB $ARMED $NGSANE_WAITFORJOB -d -k $CONFIG -t $TASK_FASTQSCREEN -i $INPUT_FASTQSCREEN -e $READONE.$FASTQ \
            -n $NODES_FASTQSCREEN -c $CPU_FASTQSCREEN -m $MEMORY_FASTQSCREEN"G" -w $WALLTIME_FASTQSCREEN \
            --command "$NGSANE_BASE/mods/fastqscreen.sh -k $CONFIG -f <FILE>  -o $OUT/<DIR>/$TASK_FASTQSCREEN"
        
    
    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then

        NGSANE_REPORT_HEADER "Fastqscreen" "$TASK_FASTQSCREEN" "fastqscreen.sh"

        NGSANE_REPORT_TABLE "$TASK_FASTQSCREEN" \
            "-" \
            "$OUT/<DIR>/$TASK_FASTQSCREEN"  \
            "_screen.txt" \
            "FIGURE:Distribution:100:<SAMPLE>_screen.png:60:1"\
            "DYNAMIC_ROWS:3,-2::awk '{print \$8}'" 


        NGSANE_REPORT_FOOTER   
    fi
fi	

	
