#!/bin/bash -e

################################################################################
#   Assessing chromatin interactions with fit-hi-c
# IN : $SOURCE/$dir/hicup/*$FRAGMENTLIST
# OUT: $OUT/$dir/hicup/*.spline_pass1.q05.txt.gz
################################################################################

if [ -n "$RUNFITHIC" ]; then
    if [ -z "$TASK_FITHIC" ] || [ -z "$NODES_FITHIC" ] || [ -z "$CPU_FITHIC" ] || [ -z "$MEMORY_FITHIC" ] || [ -z "$WALLTIME_FITHIC" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi

    $QSUB $ARMED -r -k $CONFIG -t $TASK_FITHIC -i $INPUT_FITHIC -e $FRAGMENTLIST -n $NODES_FITHIC -c $CPU_FITHIC \
    	-m $MEMORY_FITHIC"G" -w $WALLTIME_FITHIC $WAITFORJOB_FITHIC \
        --command "${NGSANE_BASE}/mods/fithic.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_FITHIC"

fi