#!/bin/bash -e

################################################################################
#   Peak generation using fseq
#
# IN:$SOURCE/$dir/$INPUT_FSEQ/*asd.bam
# OUT: $OUT/$dir/fseq/*.bw
################################################################################

if [ -n "$RUNFSEQ" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    if [ -z "$TASK_FSEQ" ] || [ -z "$NODES_FSEQ" ] || [ -z "$CPU_FSEQ" ] || [ -z "$MEMORY_FSEQ" ] || [ -z "$WALLTIME_FSEQ" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi

    $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_FSEQ -i $INPUT_FSEQ -e $ASD.bam \
        -n $NODES_FSEQ -c $CPU_FSEQ -m $MEMORY_FSEQ"G" -w $WALLTIME_FSEQ \
        --command "${NGSANE_BASE}/mods/fseq.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_FSEQ"
fi
