#!/bin/bash -e

################################################################################
#   Depth of Coverage
# IN: */bwa/*.bam
# OUT: */bwa_var/*.clean.vcf
################################################################################

if [ -n "$RUNGATKDOC" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # check if resources are properly defined
        if [ -z "$TASK_GATKDOC" ] || [ -z "$NODES_GATKDOC" ] || [ -z "$CPU_GATKDOC" ] || [ -z "$MEMORY_GATKDOC" ] || [ -z "$WALLTIME_GATKDOC" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi


        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_GATKDOC -i $INPUT_GATKDOC -e $ASR.bam \
    	   -n $NODES_GATKDOC -c $CPU_GATKDOC -m $MEMORY_GATKDOC"G" -w $WALLTIME_GATKDOC \
    	   --command "${NGSANE_BASE}/mods/gatkDOC.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_GATKDOC"
	       
    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
    
        NGSANE_REPORT_HEADER "DepthOfCoverage" "$TASK_GATKDOC" "gatkDOC.sh"

        NGSANE_REPORT_TABLE "$TASK_GATKDOC" \
            "$OUT/<DIR>/$TASK_GATKDOC/" \
            ".doc.sample_summary" \
            "PATTERN:Col1::sed-n 2p | cut -f 2" \
            "PATTERN:Col2::sed-n 2p | cut -f 3" \
            "PATTERN:Col3::sed-n 2p | cut -f 4" \
            "PATTERN:Col4::sed-n 2p | cut -f 5" 
        #TODO check pattern
        
        NGSANE_REPORT_TABLE "$TASK_GATKDOC" \
            "$OUT/<DIR>/$TASK_GATKDOC/" \
            ".doc.sample_cumulative_coverage_counts" \
            "PATTERN:Col1::sed-n 2p | cut -f 2" \
            "PATTERN:Col2::sed-n 2p | cut -f 3" \
            "PATTERN:Col3::sed-n 2p | cut -f 4" \
            "PATTERN:Col4::sed-n 2p | cut -f 5" \

        NGSANE_REPORT_TABLE "$TASK_GATKDOC" \
            "$OUT/<DIR>/$TASK_GATKDOC/" \
            ".doc.sample_interval_statistics" \
            "PATTERN:Col1::sed-n 2p | cut -f 2" \
            "PATTERN:Col2::sed-n 2p | cut -f 3" \
            "PATTERN:Col3::sed-n 2p | cut -f 4" \
            "PATTERN:Col4::sed-n 2p | cut -f 5" \
            
        NGSANE_REPORT_TABLE "$TASK_GATKDOC" \
            "$OUT/<DIR>/$TASK_GATKDOC/" \
            "$ASR.bam.stats"" \
            "PATTERN:Total reads::sed -n 1p | cut -d' ' -f 1" \
            "PATTERN:Paired::sed-n 2p | cut -f 3" \
            "CALCULATE:%:40:#3*100/#2" \
            "PATTERN:On target::sed-n 2p | cut -f 5" \
            "CALCULATE:%:40:#5*100/#2" \
            "PATTERN:Paired on target::sed-n 2p | cut -f 5" \
            "CALCULATE:%:40:#7*100/#2"
                                            
        NGSANE_REPORT_FOOTER   
  
    fi
fi	

	