#!/bin/bash -e

################################################################################
#   call indels with GATK -- call one vcf file over all folders
################################################################################

if [ -n "$RUNGATKVAR" ] || [ -n "$NGSANE_PIPELINECALL" ]; then

#    TODO: make sure it shorter than 64
    NAME=$(echo ${DIR[@]}|sed 's/ /_/g')
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        if [ -z "$TASK_GATKVAR" ] || [ -z "$NODES_GATKVAR" ] || [ -z "$CPU_GATKVAR" ] || [ -z "$MEMORY_GATKVAR" ] || [ -z "$WALLTIME_GATKVAR" ]; then 
            echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; 
        fi
        
        
        $QSUB $ARMED $NGSANE_WAITFORJOB -r -d -k $CONFIG -t $TASK_GATKVAR -i $INPUT_GATKVAR  -e $ASR.bam -n $NODES_GATKVAR \
            -c $CPU_GATKVAR -m $MEMORY_GATKVAR"G" -w $WALLTIME_GATKVAR \
            --postcommand "${NGSANE_BASE}/mods/gatkVARs.sh -k $CONFIG \
                            -i <FILE> -t $CPU_GATKVAR \
                            -r $FASTA -d $DBSNPVCF -o $OUT/$TASK_GATKVAR/$NAME -n $NAME \
                            -H $HAPMAPVCF" #-K $ONEKGVCF"
                        

    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then

        NGSANE_REPORT_HEADER "VarCalls" "$TASK_GATKVAR" "gatkVARs.sh"

        NGSANE_REPORT_TABLE "${TASK_GATKVAR}" \
            "$OUT/$TASK_GATKVAR/$NAME" \
            ".filter.snps.eval.txt" \
            "PATTERN:Total::fgrep -w 'CountVariants' | sed -n 3p | tr -s ' ' '\t' | cut -f7" \
            "PATTERN:Known::fgrep -w 'CompOverlap' | sed -n 4p | tr -s ' ' '\t' | cut -f6" \
            "PATTERN:SNPdb Conc::fgrep -w 'CompOverlap' | sed -n 4p | tr -s ' ' '\t' | cut -f11" \
            "PATTERN:Variant Rate/Bp::fgrep -w 'CountVariants' | sed -n 4p | tr -s ' ' '\t' | cut -f11" \
            "PATTERN:Het/Hom::fgrep -w 'CountVariants' | sed -n 4p | tr -s ' ' '\t' | cut -f27" \
            "PATTERN:Novel::fgrep -w 'CompOverlap' | sed -n 5p | tr -s ' ' '\t' | cut -f6" \
            "PATTERN:Variant Rate/Bp::fgrep -w 'CountVariants' | sed -n 5p | tr -s ' ' '\t' | cut -f11" \
            "PATTERN:Het/Hom::fgrep -w 'CountVariants' | sed -n 5p | tr -s ' ' '\t' | cut -f27"


        NGSANE_REPORT_TABLE "${TASK_GATKVAR}" \
            "$OUT/$TASK_GATKVAR/$NAME" \
            ".recalfilt.snps.eval.txt" \
            "PATTERN:Total::fgrep -w 'CountVariants' | sed -n 3p | tr -s ' ' '\t' | cut -f7" \
            "PATTERN:Known::fgrep -w 'CompOverlap' | sed -n 4p | tr -s ' ' '\t' | cut -f6" \
            "PATTERN:SNPdb Conc::fgrep -w 'CompOverlap' | sed -n 4p | tr -s ' ' '\t' | cut -f11" \
            "PATTERN:Variant Rate/Bp::fgrep -w 'CountVariants' | sed -n 4p | tr -s ' ' '\t' | cut -f11" \
            "PATTERN:Het/Hom::fgrep -w 'CountVariants' | sed -n 4p | tr -s ' ' '\t' | cut -f27" \
            "PATTERN:Novel::fgrep -w 'CompOverlap' | sed -n 5p | tr -s ' ' '\t' | cut -f6" \
            "PATTERN:Variant Rate/Bp::fgrep -w 'CountVariants' | sed -n 5p | tr -s ' ' '\t' | cut -f11" \
            "PATTERN:Het/Hom::fgrep -w 'CountVariants' | sed -n 5p | tr -s ' ' '\t' | cut -f27"


        NGSANE_REPORT_TABLE "${TASK_GATKVAR}" \
            "$OUT/$TASK_GATKVAR/$NAME" \
            ".filter.indel.eval.txt" \
            "PATTERN:Total::fgrep -w 'CountVariants' | sed -n 3p | tr -s ' ' '\t' | cut -f7" \
            "PATTERN:Known::fgrep -w 'CompOverlap' | sed -n 4p | tr -s ' ' '\t' | cut -f6" \
            "PATTERN:SNPdb Conc::fgrep -w 'CompOverlap' | sed -n 4p | tr -s ' ' '\t' | cut -f11" \
            "PATTERN:Variant Rate/Bp::fgrep -w 'CountVariants' | sed -n 4p | tr -s ' ' '\t' | cut -f11" \
            "PATTERN:Het/Hom::fgrep -w 'CountVariants' | sed -n 4p | tr -s ' ' '\t' | cut -f27" \
            "PATTERN:Novel::fgrep -w 'CompOverlap' | sed -n 5p | tr -s ' ' '\t' | cut -f6" \
            "PATTERN:Variant Rate/Bp::fgrep -w 'CountVariants' | sed -n 5p | tr -s ' ' '\t' | cut -f11" \
            "PATTERN:Het/Hom::fgrep -w 'CountVariants' | sed -n 5p | tr -s ' ' '\t' | cut -f27"


        NGSANE_REPORT_FOOTER 
        
    fi
fi	

	