#!/bin/bash -e

################################################################################
#   Mapping using HiCUP
# IN : $SOURCE/fastq/$dir/*$READONE$FASTQ
# OUT: $OUT/$dir/hicup/*_uniques.bam
################################################################################

if [ -n "$RUNHICUP" ]; then
    if [ -z "$TASK_HICUP" ] || [ -z "$NODES_HICUP" ] || [ -z "$CPU_HICUP" ] || [ -z "$MEMORY_HICUP" ] || [ -z "$WALLTIME_HICUP" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
    
    if [ ! -f ${FASTA%.*}.1.ebwt ];then
        # submit job for index generation if necessary
        INDEXJOBIDS=$(
            $QSUB $ARMED -k $CONFIG -t $TASK_HICUP -i $INPUT_HICUP -e $READONE.$FASTQ -n $NODES_HICUP -c $CPU_HICUP \
    	   -m $MEMORY_HICUP"G" -w $WALLTIME_HICUP $WAITFORJOB_HICUP \
    	   --commontask indexGenome \
           --command "${NGSANE_BASE}/mods/bowtieIndex.sh -k $CONFIG"
        ) && echo -e "$INDEXJOBIDS"
        INDEXJOBIDS=$(waitForJobIds "$INDEXJOBIDS")
    else
        INDEXJOBIDS=$WAITFORJOB_HICUP
    fi
    
    if [ ! -f $OUT/common/$TASK_HICUP/Digest_${REFERENCE_NAME}_${HICUP_RENZYME1}_${HICUP_RENZYME2}.txt ];then
        JOBIDS=$( 
        $QSUB $ARMED -k $CONFIG -t $TASK_HICUP -i $INPUT_HICUP -e $READONE.$FASTQ -n $NODES_HICUP -c 1 \
        	-m $MEMORY_HICUP"G" -w $WALLTIME_HICUP $INDEXJOBIDS $WAITFORJOB_HICUP \
        	--commontask digestGenome \
            --command "${NGSANE_BASE}/mods/hicupDigestGenome.sh -k $CONFIG" 
        ) && echo -e "$JOBIDS"
        JOBIDS=$(waitForJobIds "$JOBIDS")

    else
        JOBIDS=$WAITFORJOB_HICUP
    fi

    $QSUB $ARMED -k $CONFIG -t $TASK_HICUP -i $INPUT_HICUP -e $READONE.$FASTQ -n $NODES_HICUP -c $CPU_HICUP \
    	-m $MEMORY_HICUP"G" -w $WALLTIME_HICUP $JOBIDS \
        --command "${NGSANE_BASE}/mods/hicup.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_HICUP"

fi