#!/bin/bash -e

################################################################################
#   Trigger command for individual IDR
#
# IN : $SOURCE/$dir/INPUT_IDR/*.narrowPeak
# OUT: $OUT/$dir/TASK_IDR/*.bed
################################################################################

if [ -n "$RUNIDR" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    # HPC variables as defined in the corresponding resource script at NGSANE_BASE/conf/header.d/IDR
    if [ -z "$TASK_IDR" ] || [ -z "$NODES_IDR" ] || [ -z "$CPU_IDR" ] || [ -z "$MEMORY_IDR" ] || [ -z "$WALLTIME_IDR" ]; then 
        echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; 
    fi
    
    $QSUB $ARMED $NGSANE_WAITFORJOB -d -r -k $CONFIG -t $TASK_IDR -i $INPUT_IDR -e *$BED \
        -n $NODES_IDR -c $CPU_IDR -m $MEMORY_IDR"G" -w $WALLTIME_IDR \
        --postname postcommand$IDR \
        --postcommand "${NGSANE_BASE}/mods/idr.sh -f <FILE> -k $CONFIG"
                         
fi
