#!/bin/bash -e

################################################################################
#  ChIP-seq analysis with MACS2
#
# IN: $SOURCE/$dir/bowtie/*.bam
# OUT: $OUT/$dir/macs2/
################################################################################
if [ -n "$RUNMACS2" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # check if resources are properly defined
        if [ -z "$TASK_MACS2" ] || [ -z "$NODES_MACS2" ] || [ -z "$CPU_MACS2" ] || [ -z "$MEMORY_MACS2" ] || [ -z "$WALLTIME_MACS2" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
    
        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_MACS2 -i $INPUT_MACS2 -e $ASD.bam \
            -n $NODES_MACS2 -c $CPU_MACS2 -m $MEMORY_MACS2"G" -w $WALLTIME_MACS2 \
            --command "${NGSANE_BASE}/mods/macs2.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_MACS2"
    
    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then

        NGSANE_REPORT_HEADER "Macs2" "$TASK_MACS2" "macs2.sh" "_peaks.bed"

        NGSANE_REPORT_TABLE "$TASK_MACS2" \
            "$OUT/<DIR>/$TASK_MACS2"  \
            ".summary.txt" \
            "PATTERN:Control::fgrep 'ChIP input' | awk '{print \$(NF)}'" \
            "PATTERN:IP reads (filtered)::egrep '(tags|fragments) after filtering in treatment' | tail -n 1 | awk '{print \$(NF)}'" \
            "PATTERN:Control reads (filtered)::egrep '(tags|fragments) after filtering in control' | tail -n 1 | awk '{print \$(NF)}'" \
            "PATTERN:Paired peaks:100:fgrep 'number of paired peaks' | tail -n 1 | awk '{print \$(NF)}'" \
            "PATTERN:Fragment size:100:fgrep 'Determined fragment size'  | tail -n 1 | awk '{print \$(NF-1)}'" \
            "PATTERN:Refined summits::fgrep 'Final number of refined summits' | tail -n 1 | awk '{print \$(NF-1)}'" \
            "PATTERN:Nucleotides covered::fgrep 'Nucleotides covered' | awk '{print \$(NF)}'" \
            "FIGURE::60:<SAMPLE>.R_model-0.png:60:1" \
            "FIGURE::60:<SAMPLE>.R_model-1.png:60:1" 

        NGSANE_REPORT_FOOTER 
  
    fi
fi	

	