#!/bin/bash -e

################################################################################
#  ChIP-seq analysis with MACS2
#
# IN: $SOURCE/$dir/bowtie/*.bam
# OUT: $OUT/$dir/macs2/
################################################################################
if [ -n "$RUNMACS2" ]; then
    if [ -z "$TASK_MACS2" ] || [ -z "$NODES_MACS2" ] || [ -z "$CPU_MACS2" ] || [ -z "$MEMORY_MACS2" ] || [ -z "$WALLTIME_MACS2" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi

    $QSUB $ARMED -r -k $CONFIG -t $TASK_MACS2 -i $INPUT_MACS2 -e $ASD.bam -n $NODES_MACS2 -c $CPU_MACS2 -m $MEMORY_MACS2"G" -w $WALLTIME_MACS2 \
	   --command "${NGSANE_BASE}/mods/macs2.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_MACS2"
fi