#!/bin/bash -e

################################################################################
#  ChIP-seq analysis with peakranger
#
# IN: $SOURCE/$dir/bowtie/*.bam
# OUT: $OUT/$dir/peakranger/
################################################################################
if [ -n "$RUNPEAKRANGER" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # check if resources are properly defined
        if [ -z "$TASK_PEAKRANGER" ] || [ -z "$NODES_PEAKRANGER" ] || [ -z "$CPU_PEAKRANGER" ] || [ -z "$MEMORY_PEAKRANGER" ] || [ -z "$WALLTIME_PEAKRANGER" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
    
        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_PEAKRANGER -i $INPUT_PEAKRANGER -e $ASD.bam \
            -n $NODES_PEAKRANGER -c $CPU_PEAKRANGER -m $MEMORY_PEAKRANGER"G" -w $WALLTIME_PEAKRANGER \
            --command "${NGSANE_BASE}/mods/peakranger.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_PEAKRANGER"
            
    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then

        NGSANE_REPORT_HEADER "Peakranger" "$TASK_PEAKRANGER" "peakranger.sh" "_region.bed"

        NGSANE_REPORT_TABLE "$TASK_PEAKRANGER" \
            "$OUT/<DIR>/$TASK_PEAKRANGER"  \
            ".summary.txt" \
            "PATTERN:Input::fgrep 'ChIP input' | awk '{print \$(NF)}'" \
            "PATTERN:Total reads::fgrep 'Total reads' | awk '{print \$(NF)}'" \
            "PATTERN:Unique::fgrep 'Unique reads' | awk '{print \$(NF)}'" \
            "CALCULATE:Unique %:80:#4*100/#3" \
            "PATTERN:Noise rate:100:fgrep 'Estimated noise rate' | awk '{print \$(NF)}'" \
            "PATTERN:Library complexity:100:fgrep 'Library complexity' | sed 's/.* \([0-9]*\.[0-9]\+\)%/\1/g'" \
            "PATTERN:Peaks::fgrep 'Peaks' | awk '{print \$(NF)}'" \
            "PATTERN:Nucleotides covered::fgrep 'Nucleotides covered' | awk '{print \$(NF)}'"

        NGSANE_REPORT_FOOTER 
  
    fi
fi	

	