#!/bin/bash -e

################################################################################ 
#   Pindel
################################################################################

if [ -n "$RUNPINDEL" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # check if resources are properly defined
        if [ -z "$TASK_PINDEL" ] || [ -z "$NODES_PINDEL" ] || [ -z "$CPU_PINDEL" ] || [ -z "$MEMORY_PINDEL" ] || [ -z "$WALLTIME_PINDEL" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
    
        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $INPUT_PINDEL-$TASK_PINDEL -i $INPUT_PINDEL -e $ASD.bam \
            -n $NODES_PINDEL -c $CPU_PINDEL -m $MEMORY_PINDEL"G" -w $WALLTIME_PINDEL \
    		--postnodes $NODES_VARCOLLECT --postcpu $CPU_VARCOLLECT \
    		--postwalltime $WALLTIME_VARCOLLECT --postmemory $MEMORY_VARCOLLECT"G" \
            --command "${NGSANE_BASE}/mods/pindel.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$INPUT_PINDEL-$TASK_PINDEL" \
    		--postcommand "${NGSANE_BASE}/mods/variantcollect.sh -k $CONFIG -f <FILE> -i1 $INPUT_PINDEL \
    				-i2 ${INPUT_PINDEL}-$TASK_PINDEL -o $OUT/variant/${INPUT_PINDEL}-${TASK_PINDEL}-<DIR> "

    
    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then

        # start a new section for a mod
        NGSANE_REPORT_HEADER "Structural Variants (Pindel)" "$TASK_PINDEL" "pindel.sh,variantcollect.sh"

        NGSANE_REPORT_TABLE "$TASK_PINDEL" \
            "$OUT/variant/${INPUT_PINDEL}-${TASK_PINDEL}-<DIR>" \
            ".eval.txt" \
            "PATTERN:Total::fgrep -w 'CountVariants' | sed -n 3p | awk -F' ' '{print $7}'" \
            "PATTERN:Known::fgrep -w 'CompOverlap' | sed -n 4p | awk -F' ' '{print $6}'" \
            "PATTERN:SNPdb Conc::fgrep -w 'CompOverlap' | sed -n 4p | awk -F' ' '{print $11}'" \
            "PATTERN:Variant Rate/Bp::fgrep -w 'CountVariants' | sed -n 4p | awk -F' ' '{print $11}'" \
            "PATTERN:Het/Hom::fgrep -w 'CountVariants' | sed -n 4p | awk -F' ' '{print $27}'" \
            "PATTERN:Novel::fgrep -w 'CompOverlap' | sed -n 5p | awk -F' ' '{print $6}'" \
            "PATTERN:Variant Rate/Bp::fgrep -w 'CountVariants' | sed -n 5p | awk -F' ' '{print $11}'" \
            "PATTERN:Het/Hom::fgrep -w 'CountVariants' | sed -n 5p | awk -F' ' '{print $27}'"

        # finish the section
        NGSANE_REPORT_FOOTER 
        
    fi
fi	

	