#!/bin/bash -e

################################################################################ 
#   Pindel
################################################################################

if [ -n "$RUNPINDEL" ]; then

    $QSUB $ARMED -r -k $CONFIG -t $INPUT_PINDEL-$TASK_PINDEL -i $INPUT_PINDEL -e $ASD.bam \
        -n $NODES_PINDEL -c $CPU_PINDEL -m $MEMORY_PINDEL"G" -w $WALLTIME_PINDEL \
		--postnodes $NODES_VARCOLLECT --postcpu $CPU_VARCOLLECT \
		--postwalltime $WALLTIME_VARCOLLECT --postmemory $MEMORY_VARCOLLECT"G" \
        --command "${NGSANE_BASE}/mods/pindel.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$INPUT_PINDEL-$TASK_PINDEL" \
		--postcommand "${NGSANE_BASE}/mods/variantcollect.sh -k $CONFIG -f <FILE> -i1 $INPUT_PINDEL \
				-i2 ${INPUT_PINDEL}-$TASK_PINDEL -o $OUT/variant/${INPUT_PINDEL}-${TASK_PINDEL}-<DIR> "

fi