#!/bin/bash -e

################################################################################
#   Pool bam files (e.g. replicates)
#
# IN : $SOURCE/TASK_BOWTIE/PATTERN*$ASD.bam
# OUT: $OUT/TASK_BOWTIE/_pooled*$ASD.bam
################################################################################

if [ -n "$RUNPOOLBAMS" ] || [ -n "$NGSANE_PIPELINECALL" ]; then

    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
    

        # check if resources are properly defined
        if [ -z "$TASK_POOLBAMS" ] || [ -z "$NODES_POOLBAMS" ] || [ -z "$CPU_POOLBAMS" ] || [ -z "$MEMORY_POOLBAMS" ] || [ -z "$WALLTIME_POOLBAMS" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi

        $QSUB $ARMED $NGSANE_WAITFORJOB -d -r -k $CONFIG -t $TASK_POOLBAMS -i $INPUT_POOLBAMS -e $ASD.bam -n $NODES_POOLBAMS \
    	    -c $CPU_POOLBAMS -m $MEMORY_POOLBAMS"G" -w $WALLTIME_POOLBAMS \
        	--postname postcommand${POOLED_DATA_NAME} \
    	    --postcommand "${NGSANE_BASE}/mods/poolBams.sh -k $CONFIG" 
 
    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then


        # start a new section for a mod
        NGSANE_REPORT_HEADER "Pool Bams" "$TASK_POOLBAMS" "bowtie2.sh" "$ASD.bam"

        # add as many tables as needed. One table per result file
        NGSANE_REPORT_TABLE "$TASK_POOLBAMS" \
            "$OUT/<DIR>/$TASK_POOLBAMS"  \
            "$ASD.bam.stats" \
            "PATTERN:Total reads:sed -n 1p | cut -d' ' -f 1" \
            "PATTERN:Qfail:sed -n 1p | cut -d' ' -f 3" \
            "PATTERN:Duplicates:sed -n 2p | cut -d' ' -f 1" \
            "CALCULATE:Duplicates %:#4*100/#2" \
            "PATTERN:Mapped:sed -n 3p | cut -d' ' -f 1" \
            "CALCULATE:Mapped %:#6*100/#2" \
            "PATTERN:Paired:sed -n 7p | cut -d' ' -f 1" \
            "CALCULATE:Paired %:#8*100/#2" \
            "PATTERN:Singletons:sed -n 9p | cut -d' ' -f 1" 
        
        # finish the section
        NGSANE_REPORT_FOOTER 
        
    fi
fi

