#!/bin/bash -e

################################################################################ 
#   recalibrate quality scores
#   http://www.broadinstitute.org/gsa/wiki/index.php/Base_quality_score_recalibration
#   http://www.broadinstitute.org/gsa/wiki/index.php/Local_realignment_around_indels
#   http://picard.sourceforge.net/command-line-overview.shtml#FixMateInformation
#   full pipe: http://www.broadinstitute.org/gsa/wiki/index.php/Whole_genome,_deep_coverage
# IN:$SOURCE/$dir/fastq/*$READONE.fastq
# OUT: $OUT/$dir/reCal/*$ASR.bam
################################################################################

if [ -n "$RUNREALRECAL" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # check if resources are properly defined

        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_RECAL -i $INPUT_REALRECAL -e $ASD.bam \
            -n $NODES_RECAL -c $CPU_RECAL -m $MEMORY_RECAL"G" -w $WALLTIME_RECAL \
            --command "${NGSANE_BASE}/mods/reCalAln.sh -k $CONFIG -f <FILE> -r $FASTA -d $DBSNPVCF -o $OUT/<DIR>/$TASK_RECAL"

    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then

        NGSANE_REPORT_HEADER "Recalibrate + Realign" "$TASK_RECAL" "reCalAln.sh"

        NGSANE_REPORT_TABLE "$TASK_RECAL" \
            "$OUT/<DIR>/$TASK_RECAL"  \
            "$ASR.bam.stats" \
            "LINK:<SAMPLE>$ASD.bam.html" \
            "PATTERN:Total reads::sed -n 1p | cut -d' ' -f 1" \
            "PATTERN:Qfail::sed -n 1p | cut -d' ' -f 3" \
            "PATTERN:Duplicates::sed -n 2p | cut -d' ' -f 1" \
            "CALCULATE:Duplicates %:80:#4*100/#2" \
            "PATTERN:Mapped::sed -n 3p | cut -d' ' -f 1" \
            "CALCULATE:Mapped %:70:#6*100/#2" \
            "PATTERN:Mapped pairs::sed -n 7p | cut -d' ' -f 1 | xargs echo 0.5* | bc " \
            "CALCULATE:Mapped pairs %:70:#8*2*100/#2" \
            "PATTERN:Singletons::sed -n 9p | cut -d' ' -f 1" 

        NGSANE_REPORT_FOOTER 
        
    fi
fi	

	