#!/bin/bash -e

################################################################################
#   Variance calling
# IN: */bwa/*.bam
# OUT: */bwa_var/*.clean.vcf
################################################################################

if [ -n "$RUNSAMVAR" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # check if resources are properly defined
    if [ -z "$TASK_SAMVAR" ] || [ -z "$NODES_SAMVAR" ] || [ -z "$CPU_SAMVAR" ] || [ -z "$MEMORY_SAMVAR" ] || [ -z "$WALLTIME_SAMVAR" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
    
        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $INPUT_SAMVAR-$TASK_SAMVAR -i $INPUT_SAMVAR -e $ASD.bam \
            -n $NODES_SAMVAR -c $CPU_SAMVAR -m $MEMORY_SAMVAR'G' -w $WALLTIME_SAMVAR \
    		--postnodes $NODES_VARCOLLECT --postcpu $CPU_VARCOLLECT \
    		--postwalltime $WALLTIME_VARCOLLECT --postmemory $MEMORY_VARCOLLECT"G" \
            --command "${NGSANE_BASE}/mods/samSNPs.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$INPUT_SAMVAR-$TASK_SAMVAR" \
    	    --postcommand "${NGSANE_BASE}/mods/variantcollect.sh -k $CONFIG -f <FILE> -i1 $INPUT_SAMVAR \
    				-i2 $INPUT_SAMVAR-$TASK_SAMVAR -o $OUT/variant/${INPUT_SAMVAR}-$INPUT_SAMVAR-$TASK_SAMVAR-<DIR>"
  	
    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then

        NGSANE_REPORT_HEADER "SamVar" "$TASK_SAMVAR" "samSNPs.sh,variantcollect.sh"

        NGSANE_REPORT_TABLE "$TASK_GATKVAR SNP" \
            "$OUT/variant/${INPUT_SAMVAR}-$INPUT_SAMVAR-$TASK_SAMVAR-<DIR>" \
            ".filter.snps.eval.txt" \
            "PATTERN:Total::fgrep -w 'CountVariants' | sed -n 3p | sed -e 's/ \+/\t/g' | cut -f7" \
            "PATTERN:Known::fgrep -w 'CompOverlap' | sed -n 4p | sed -e 's/ \+/\t/g' | cut -f6" \
            "PATTERN:SNPdb Conc::fgrep -w 'CompOverlap' | sed -n 4p | sed -e 's/ \+/\t/g' | cut -f11" \
            "PATTERN:Variant Rate/Bp::fgrep -w 'CountVariants' | sed -n 4p | sed -e 's/ \+/\t/g' | cut -f11" \
            "PATTERN:Het/Hom::fgrep -w 'CountVariants' | sed -n 4p | sed -e 's/ \+/\t/g' | cut -f27" \
            "PATTERN:Novel::fgrep -w 'CompOverlap' | sed -n 5p | sed -e 's/ \+/\t/g' | cut -f6" \
            "PATTERN:Variant Rate/Bp::fgrep -w 'CountVariants' | sed -n 5p | sed -e 's/ \+/\t/g' | cut -f11" \
            "PATTERN:Het/Hom::fgrep -w 'CountVariants' | sed -n 5p | sed -e 's/ \+/\t/g' | cut -f27"

        NGSANE_REPORT_FOOTER 
        
    fi
fi	

	