#!/bin/bash -e

################################################################################
#  Fusion search tophat
#
# IN : $SOURCE/$dir/fastq/*read1.fastq
# OUT: $OUT/$dir/tophatfusion_out/*
################################################################################       

if [ -n "$RUNFUSION" ]; then
    if [ -z "$TASK_FUSION" ] || [ -z "$NODES_FUSION" ] || [ -z "$CPU_FUSION" ] || [ -z "$MEMORY_FUSION" ] || [ -z "$WALLTIME_FUSION" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi

    if [ ! -f ${FASTA%.*}.1.bt2 ];then
        # submit job for index generation if necessary
        INDEXJOBIDS=$(
            $QSUB $ARMED -k $CONFIG -t $TASK_FUSION -i $INPUT_FUSION -e $READONE.$FASTQ -n $NODES_FUSION -c $CPU_FUSION -m $MEMORY_FUSION"G" $WAITFORJOB_FUSION \
            -w $WALLTIME_FUSION --commontask indexGenome \
            --command "${NGSANE_BASE}/mods/bowtie2Index.sh -k $CONFIG"
        ) && echo -e "$INDEXJOBIDS"
        INDEXJOBIDS=$(waitForJobIds "$INDEXJOBIDS")
    else
        INDEXJOBIDS=""
    fi
    
    $QSUB $ARMED -k $CONFIG -t $TASK_FUSION -i $INPUT_FUSION -e $READONE.$FASTQ -n $NODES_FUSION -c $CPU_FUSION -m $MEMORY_FUSION"G" -w $WALLTIME_FUSION $INDEXJOBIDS \
        --command "${NGSANE_BASE}/mods/fusion.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_FUSION/<NAME>"

fi