#!/bin/bash -e

################################################################################
#   Transcriptome assembly without a Reference (Trinity)
# IN : $SOURCE/$dir/fastq/*read1.fastq
# OUT: $OUT/$dir/trinity/*.Trinity.fasta.gz
################################################################################

#  echo -e "        _       _     _ _"
#  echo -e "       | |_ ___|_|___|_| |_ _ _"
#  echo -e "       |  _|  _| |   | |  _| | |"
#  echo -e "       |_| |_| |_|_|_|_|_| |_  |"
#  echo -e "   DeNovo Transcriptome    |___|  "
#  echo -e "   Assembly without a reference genome"
#  echo -e ""

if [ -n "$RUNTRINITY" ]; then
    
    #  ##########   Inchworm   ###########
    
    JOBIDS=$( 
        RUNINCHWORM="1"
        . $NGSANE_BASE/mods/run.d/TRINITY_INCHWORM
        RUNINCHWORM=
         
    ) && echo -e "$JOBIDS"
    JOBIDS_TRINITY_INCHWORM=$(waitForJobIds "$JOBIDS")

    #  ##########   Chrysalis   ###########

    JOBIDS=$( 
        RUNCHRYSALIS="1"
        WAITFORJOB_TRINITY_CHRYSALIS=$JOBIDS_TRINITY_INCHWORM
        . $NGSANE_BASE/mods/run.d/TRINITY_CHRYSALIS
        RUNCHRYSALIS=
    ) && echo -e "$JOBIDS"
    JOBIDS_TRINITY_CHRYSALIS=$(waitForJobIds "$JOBIDS")

    #  ##########   Butterfly   ###########

    JOBIDS=$( 
        RUNBUTTERFLY=1
        WAITFORJOB_TRINITY_BUTTERFLY=$JOBIDS_TRINITY_CHRYSALIS
        . $NGSANE_BASE/mods/run.d/TRINITY_BUTTERFLY
        RUNBUTTERFLY=
    ) && echo -e "$JOBIDS"
    JOBIDS_TRINITY_BUTTERFLY=$(waitForJobIds "$JOBIDS")
    

fi
