#!/bin/bash -e

################################################################################
#   call indels with GATK -- call one vcf file over all folders
################################################################################

if [ -n "$RUNVARCALLS" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        NAME=$(echo ${DIR[@]}|sed 's/ /_/g')
        $QSUB $ARMED $NGSANE_WAITFORJOB -r -d -k $CONFIG -t $TASK_GATKVAR -i $INPUT_GATKVAR  -e $ASR.bam -n $NODES_GATKVAR \
            -c $CPU_GATKVAR -m $MEMORY_GATKVAR"G" -w $WALLTIME_GATKVAR \
            --postcommand "${NGSANE_BASE}/mods/gatkVARs.sh -k $CONFIG \
                            -i <FILE> -t $CPU_GATKVAR \
                            -r $FASTA -d $DBSNPVCF -o $OUT/$TASK_GATKVAR/$NAME -n $NAME \
                            -H $HAPMAPVCF" #-K $ONEKGVCF"
                        

    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then

        # start a new section for a mod
        NGSANE_REPORT_HEADER "VARCALLS" "$TASK_GATKVAR" "gatkVARs.sh"

        echo "[NOTE] the gatkVARs.sh mod does not provide a report"
        
        # finish the section
        NGSANE_REPORT_FOOTER 
        
    fi
fi	

	