#!/bin/bash -e

################################################################################
#   call indels with GATK -- call one vcf file over all folders
################################################################################

if [ -n "$RUNVARCALLS" ]; then
    NAME=$(echo ${DIR[@]}|sed 's/ /_/g')
    $QSUB $ARMED -r -d -k $CONFIG -t $TASK_GATKVAR -i $INPUT_GATKVAR  -e $ASR.bam -n $NODES_GATKVAR \
        -c $CPU_GATKVAR -m $MEMORY_GATKVAR"G" -w $WALLTIME_GATKVAR $WAITFORJOB_GATKVAR \
        --postcommand "${NGSANE_BASE}/mods/gatkVARs.sh -k $CONFIG \
                        -i <FILE> -t $CPU_GATKVAR \
                        -r $FASTA -d $DBSNPVCF -o $OUT/$TASK_GATKVAR/$NAME -n $NAME \
                        -H $HAPMAPVCF" #-K $ONEKGVCF"
fi