#!/bin/bash -e

################################################################################
#   Mapping using Yara
#
# IN:$SOURCE/$dir/fastq/*read1.fastq
# OUT: $OUT/$dir/yara/*.bam
################################################################################

if [ -n "$RUNYARA" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
        
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # check if resources are properly defined
        if [ -z "$TASK_YARA" ] || [ -z "$NODES_YARA" ] || [ -z "$CPU_YARA" ] || [ -z "$MEMORY_YARA" ] || [ -z "$WALLTIME_YARA" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
        
        if [ ! -f ${FASTA%.*}.sa.val ];then
            # submit job for index generation if necessary
            INDEXJOBIDS=$(
                $QSUB $ARMED $NGSANE_WAITFORJOB -k $CONFIG -t $TASK_YARA -i $INPUT_YARA -e $READONE.$FASTQ \
                -n $NODES_YARA -c $CPU_YARA -m $MEMORY_YARA"G" \
                -w $WALLTIME_YARA --commontask indexGenome \
                --command "${NGSANE_BASE}/mods/yaraIndex.sh -k $CONFIG"
            ) && echo -e "$INDEXJOBIDS"
            INDEXJOBIDS=$(waitForJobIds "$INDEXJOBIDS")
        else
            INDEXJOBIDS=$NGSANE_WAITFORJOB
        fi
        
        $QSUB $ARMED -k $CONFIG -t $TASK_YARA -i $INPUT_YARA -e $READONE.$FASTQ \
            -n $NODES_YARA -c $CPU_YARA -m $MEMORY_YARA"G" -w $WALLTIME_YARA  $INDEXJOBIDS \
            --command "${NGSANE_BASE}/mods/yara.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_YARA --rgsi <DIR>"        
        
    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then

        NGSANE_REPORT_HEADER "Yara" "$TASK_YARA" "yara.sh" "$ASD.bam"

        NGSANE_REPORT_TABLE "$TASK_YARA" \
            "$OUT/<DIR>/$TASK_YARA"  \
            "$ASD.bam.stats" \
            "LINK:<SAMPLE>$ASD.bam.html" \
            "PATTERN:Total reads::sed -n 1p | cut -d' ' -f 1" \
            "PATTERN:Qfail::sed -n 1p | cut -d' ' -f 3" \
            "PATTERN:Duplicates::sed -n 2p | cut -d' ' -f 1" \
            "CALCULATE:%:40:#4*100/#2" \
            "PATTERN:Mapped::sed -n 3p | cut -d' ' -f 1" \
            "CALCULATE:%:40:#6*100/#2" \
            "PATTERN:Mapped pairs::sed -n 7p | cut -d' ' -f 1 | xargs echo 0.5* | bc " \
            "CALCULATE:%:40:#8*2*100/#2" \
            "PATTERN:Singletons::sed -n 9p | cut -d' ' -f 1" 
        
        NGSANE_REPORT_FOOTER 
        
    fi
fi