#!/bin/bash -e
# autor Fabian Buske

# This template should be used to specify the parameter for the pipelines.
# Pipelines chain together individual mods and require proper staging.
# In addition a single config file used for job submission needs to contain all 
# parameters necessary for each individual mod utilized in the pipeline.

# Copy this file and name it after your new module
# Substitute [MOD] and similar places with the appropriate variables

################################################################################
#   Trigger command for pipelines
################################################################################

: ' # [TODO] REMOVE THIS LINE

if [ -n "$RUN[PIPELINE]" ]; then
        
    JOBIDS_[MOD1]=$(NGSANE_PIPELINE_MOD "[MOD1]")
    
    JOBIDS_[MOD2]=$(NGSANE_PIPELINE_MOD "[MOD2]" "$[MOD1]")
    
    JOBIDS_[MOD3]=$(NGSANE_PIPELINE_MOD "[MOD3]" "$[MOD1]")

    JOBIDS_[MOD4]=$(NGSANE_PIPELINE_MOD "[MOD4]" "$[MOD3]")
    
fi

' # [TODO] REMOVE THIS LINE
