#!/bin/bash -e

################################################################################
#   Trigger command for individual ANNOVAR
#
# IN : $SOURCE/$dir/INPUT_ANNOVAR/*.[inputfile.suffix]
# OUT: $OUT/$dir/TASK_ANNOVAR/*.[outputfile.suffix]
################################################################################

if [ -n "$RUNANNOVAR" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # HPC variables as defined in the corresponding resource script at NGSANE_BASE/conf/header.d/ANNOVAR
        if [ -z "$TASK_ANNOVAR" ] || [ -z "$NODES_ANNOVAR" ] || [ -z "$CPU_ANNOVAR" ] || [ -z "$MEMORY_ANNOVAR" ] || [ -z "$WALLTIME_ANNOVAR" ]; then 
            echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; 
        fi


        ##ensure directory is there
        #if [ ! -d $QOUT/$TASK_ANNOVAR ]; then mkdir -p $QOUT/$TASK_ANNOVAR; fi
        #if [ ! -d $OUT/$INPUT_ANNOVAR/$TASK_ANNOVAR ]; then mkdir -p $OUT/$INPUT_ANNOVAR/$TASK_ANNOVAR; fi
        
        echo $INPUT_ANNOVAR

        $QSUB $ARMED $NGSANE_WAITFORJOB -d -k $CONFIG -t $TASK_ANNOVAR -i $INPUT_ANNOVAR -e filter.vcf \
             -n $NODES_ANNOVAR -c $CPU_ANNOVAR -m $MEMORY_ANNOVAR"G" -w $WALLTIME_ANNOVAR \
             --command "${NGSANE_BASE}/mods/annovar.sh -k $CONFIG -f <FILE> -o $OUT/$INPUT_ANNOVAR/<DIR>/$TASK_ANNOVAR"
    
                   
    ############################################################################
    # Select either of the one below to provide a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then

        # start a new section for a mod
        NGSANE_REPORT_HEADER "ANNOVAR" "$TASK_ANNOVAR" "ANNOVAR.sh,[MODPOSTCOMMAND].sh" "[PRIMARY OUTPUT FILE SUFFIX - optional]"
                   
        # 3) or provide information that there will be no 
        echo "[NOTE] the ANNOVAR.sh mod does not provide a report"

        # finish the section
        NGSANE_REPORT_FOOTER 
        
    fi
    
fi



