#!/bin/bash -e

################################################################################
#   Assessing chromatin interactions with fit-hi-c
# IN : $SOURCE/$dir/hicup/*$FRAGMENTLIST
# OUT: $OUT/$dir/hicup/*.spline_pass1.q05.txt.gz
################################################################################

if [ -n "$RUNFITHIC" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # check if resources are properly defined
        if [ -z "$TASK_FITHIC" ] || [ -z "$NODES_FITHIC" ] || [ -z "$CPU_FITHIC" ] || [ -z "$MEMORY_FITHIC" ] || [ -z "$WALLTIME_FITHIC" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
    
        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_FITHIC -i $INPUT_FITHIC -e $FRAGMENTLIST \
            -n $NODES_FITHIC -c $CPU_FITHIC -m $MEMORY_FITHIC"G" -w $WALLTIME_FITHIC \
            --command "${NGSANE_BASE}/mods/fithic.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_FITHIC"
    
    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then

        # start a new section for a mod
        NGSANE_REPORT_HEADER "Fithic" "$TASK_FITHIC" "fithic.sh"

        NGSANE_REPORT_TABLE "$TASK_FITHIC" \
            "-" \
            "$OUT/<DIR>/$TASK_FITHIC"  \
            ".log" \
            "PATTERN!Min distance!!fgrep -w 'distLowThres' | tail -n 1 | cut -f 1 | cut -d' ' -f 2" \
            "PATTERN!Max distance!!fgrep -w 'distLowThres' | tail -n 1 | cut -f 2 | cut -d' ' -f 2" \
            "PATTERN!Possible Intra In Range!!fgrep -w 'possibleIntraInRangeCount' | tail -n 1 | cut -d' ' -f 2" \
            "PATTERN!Intra In Range Count!!fgrep -w 'intraInRangeCount' | tail -n 1 | cut -f 1 | cut -d' ' -f 2" \
            "PATTERN!Intra Out Of Range Count!!fgrep -w 'intraOutOfRangeCount' | tail -n 1 | cut -f 2 | cut -d' ' -f2" \
            "PATTERN!Intra Very Proximal Count!!fgrep -w 'intraVeryProximalCount' | tail -n 1 | cut -f 3 | cut -d' ' -f2" \
            "PATTERN!Inter Count!!fgrep -w 'interCount' | tail -n 1 | cut -f 4 | cut -d' ' -f2" \
            "PATTERN!Significant interactions!!fgrep -w 'Significant interactions' | cut -d' ' -f3"

        # finish the section
        NGSANE_REPORT_FOOTER 
  
    fi
fi	

	