#!/bin/bash -e

################################################################################
#   Peak generation using fseq
#
# IN:$SOURCE/$dir/$INPUT_FSEQ/*asd.bam
# OUT: $OUT/$dir/fseq/*.bw
################################################################################

if [ -n "$RUNFSEQ" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # check if resources are properly defined
        if [ -z "$TASK_FSEQ" ] || [ -z "$NODES_FSEQ" ] || [ -z "$CPU_FSEQ" ] || [ -z "$MEMORY_FSEQ" ] || [ -z "$WALLTIME_FSEQ" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
    
        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_FSEQ -i $INPUT_FSEQ -e $ASD.bam \
            -n $NODES_FSEQ -c $CPU_FSEQ -m $MEMORY_FSEQ"G" -w $WALLTIME_FSEQ \
            --command "${NGSANE_BASE}/mods/fseq.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_FSEQ"
    
    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then

        NGSANE_REPORT_HEADER "Fseq" "$TASK_FSEQ" "fseq.sh"

        NGSANE_REPORT_TABLE "$TASK_FSEQ" \
            "-" \
            "$OUT/<DIR>/$TASK_FSEQ"  \
            ".narrowPeak" \
            "PATTERN!Peak!!wc -l | awk '{print $1}'"

        NGSANE_REPORT_FOOTER 
  
    fi
fi	

	