#!/bin/bash -e

################################################################################
#   Trigger command for individual [MOD]
#
# IN : $SOURCE/$dir/INPUT_GATK_MAPCLEAN/*.bam
# OUT: $OUT/$dir/TASK_GATK_MAPCLEAN/*.bam
################################################################################

if [ -n "$RUNGATK_MAPCLEAN" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # HPC variables as defined in the corresponding resource script at NGSANE_BASE/conf/header.d/[MOD]
        if [ -z "$TASK_GATK_MAPCLEAN" ] || [ -z "$NODES_GATK_MAPCLEAN" ] || [ -z "$CPU_GATK_MAPCLEAN" ] || [ -z "$MEMORY_GATK_MAPCLEAN" ] || [ -z "$WALLTIME_GATK_MAPCLEAN" ]; then 
            echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; 
        fi
        
    
        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_GATK_MAPCLEAN -i $INPUT_GATK_MAPCLEAN -e bam \
            -n $NODES_GATK_MAPCLEAN -c $CPU_GATK_MAPCLEAN -m $MEMORY_GATK_MAPCLEAN"G" -w $WALLTIME_GATK_MAPCLEAN \
            --command "$NGSANE_BASE/mods/gatk_mapclean.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_GATK_MAPCLEAN"

    
   

    ############################################################################
    # Select either of the one below to provide a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
        echo "[NOTE] the ubam.sh mod does not provide a report"

    fi
fi


      
                   
    ############################################################################
    # Select either of the one below to provide a report for this mod
