#!/bin/bash -e

################################################################################
#   TAD calling with domaincall
# IN : $SOURCE/$dir/fithic/*contactCounts.gz
# OUT: $OUT/$dir/hicdomaincall/*.spline_pass1.q05.txt.gz
################################################################################

if [ -n "$RUNHICDOMAINCALL" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # check if resources are properly defined
        if [ -z "$TASK_HICDOMAINCALL" ] || [ -z "$NODES_HICDOMAINCALL" ] || [ -z "$CPU_HICDOMAINCALL" ] || [ -z "$MEMORY_HICDOMAINCALL" ] || [ -z "$WALLTIME_HICDOMAINCALL" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
    
        if [ -z "$INPUT_HICDOMAINCALL_SUFFIX" ]; then echo "File suffix for input files need to be specified (INPUT_HICDOMAINCALL_SUFFIX)"; exit 1; fi

        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_HICDOMAINCALL -i $INPUT_HICDOMAINCALL -e $INPUT_HICDOMAINCALL_SUFFIX \
            -n $NODES_HICDOMAINCALL -c $CPU_HICDOMAINCALL -m $MEMORY_HICDOMAINCALL"G" -w $WALLTIME_HICDOMAINCALL \
            --command "${NGSANE_BASE}/mods/hicDomaincall.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_HICDOMAINCALL" 
         
            
    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then

        # start a new section for a mod
        NGSANE_REPORT_HEADER "Domaincall" "$TASK_HICDOMAINCALL" "hicDomaincall.sh" "txt.gz"

        NGSANE_REPORT_TABLE "$TASK_HICDOMAINCALL" \
            "-" \
            "$OUT/<DIR>/$TASK_HICDOMAINCALL"  \
            ".log" \
            "PATTERN!Possible Cis!!fgrep -w 'Possible, Intra-chr all' | tail -n 1 | cut -d'=' -f 2" \

        # finish the section
        NGSANE_REPORT_FOOTER 
  
    fi
fi	
