#!/bin/bash -e!

################################################################################
#   Trigger command for individual IDR
#
# IN : $SOURCE/$dir/INPUT_IDR/*.narrowPeak
# OUT: $OUT/$dir/TASK_IDR/*.bed
################################################################################

if [ -n "$RUNIDR" ] || [ -n "$NGSANE_PIPELINECALL" ]; then

    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        if [ -z "$TASK_IDR" ] || [ -z "$NODES_IDR" ] || [ -z "$CPU_IDR" ] || [ -z "$MEMORY_IDR" ] || [ -z "$WALLTIME_IDR" ]; then 
            echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; 
        fi
        
        $QSUB $ARMED $NGSANE_WAITFORJOB -d -r -k $CONFIG -t $TASK_IDR -i $INPUT_IDR -e *$IDR_BEDSUFFIX \
            -n $NODES_IDR -c $CPU_IDR -m $MEMORY_IDR"G" -w $WALLTIME_IDR \
            --postname postcommand$IDR \
            --postcommand "${NGSANE_BASE}/mods/idr.sh -f <FILE> -k $CONFIG"
                         
    ############################################################################
    # Select either of the one below to provide a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then

        NGSANE_REPORT_HEADER "IDR" "$TASK_IDR" "idr.sh" ".bed"

        NGSANE_REPORT_TABLE "$TASK_IDR" \
            "-" \
            "$OUT/<DIR>/$TASK_IDR"  \
            "-overlapped-peaks.txt" \
            "PATTERN!IDR Peaks!!wc -l | cut -f 1" 

        NGSANE_REPORT_FOOTER 
        
    fi
    
    # done
fi
