#!/bin/bash -e

################################################################################
#   Mapping using mrsFastUltra
#
# IN:$SOURCE/$dir/fastq/*read1.fastq
# OUT: $OUT/$dir/bowtie/*$ASD.bam
################################################################################

if [ -n "$RUNMRSFAST" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # check if resources are properly defined
        if [ -z "$TASK_MRSFAST" ] || [ -z "$NODES_MRSFAST" ] || [ -z "$CPU_MRSFAST" ] || [ -z "$MEMORY_MRSFAST" ] || [ -z "$WALLTIME_MRSFAST" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
    
        if [ ! -f $FASTA.index ];then
            # submit job for index generation if necessary
            INDEXJOBIDS=$(
                $QSUB $ARMED $NGSANE_WAITFORJOB -k $CONFIG -t $TASK_MRSFAST -i $INPUT_MRSFAST -e $READONE.$FASTQ 
                -n $NODES_MRSFAST -c $CPU_MRSFAST -m $MEMORY_MRSFAST"G" \
                -w $WALLTIME_MRSFAST --commontask indexGenome \
                --command "${NGSANE_BASE}/mods/mrsfastIndex.sh -k $CONFIG"
            ) && echo -e "$INDEXJOBIDS"
            INDEXJOBIDS=$(waitForJobIds "$INDEXJOBIDS")
        else
            INDEXJOBIDS=$WAITFORJOB_MRSFAST
        fi
        
        $QSUB $ARMED -k $CONFIG -t $TASK_MRSFAST -i $INPUT_MRSFAST -e $READONE.$FASTQ -n $NODES_MRSFAST -c $CPU_MRSFAST -m $MEMORY_MRSFAST"G" -w $WALLTIME_MRSFAST $INDEXJOBIDS \
            --command "${NGSANE_BASE}/mods/mrsfast.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_MRSFAST --rgsi <DIR>"        
            
    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then

        NGSANE_REPORT_HEADER "MrsFast Ultra" "$TASK_MRSFAST" "mrsfast.sh" "$ASD.bam"

        NGSANE_REPORT_TABLE "$TASK_MRSFAST" \
            "-" \
            "$OUT/<DIR>/$TASK_MRSFAST"  \
            "$ASD.bam.stats" \
            "LINK!<SAMPLE>$ASD.bam.html" \
            "PATTERN!Total reads!! fgrep -w 'in total' | cut -d' ' -f 1" \
            "PATTERN!Secondary!! fgrep -w 'secondary' | cut -d' ' -f 1" \
            "PATTERN!Qfail!! fgrep -w 'in total' | cut -d' ' -f 3" \
            "PATTERN!Duplicates!! fgrep -w 'duplicates' | cut -d' ' -f 1" \
            "CALCULATE!%!40!#5*100/#2" \
            "PATTERN!Mapped!! fgrep -w 'mapped' | head -n 1 | cut -d' ' -f 1" \
            "CALCULATE!%!40!#7*100/#2" \
            "PATTERN!Mapped pairs!! fgrep -w 'properly paired' | cut -d' ' -f 1 | xargs echo 0.5* | bc " \
            "CALCULATE!%!40!#9*2*100/#2" \
            "PATTERN!Singletons!! fgrep -w 'singletons' | cut -d' ' -f 1" \
            "CALCULATE!%!40!#11*100/#2"

        
        NGSANE_REPORT_FOOTER 
        
    fi
fi
