#!/bin/bash -e

################################################################################
#   Pool bam files (e.g. replicates)
#
# IN : $SOURCE/TASK_BOWTIE/PATTERN*$ASD.bam
# OUT: $OUT/TASK_POOLBAMS/*$ASD.bam
################################################################################

if [ -n "$RUNPOOLBAMS" ] || [ -n "$NGSANE_PIPELINECALL" ]; then

    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
    

        # check if resources are properly defined
        if [ -z "$TASK_POOLBAMS" ] || [ -z "$NODES_POOLBAMS" ] || [ -z "$CPU_POOLBAMS" ] || [ -z "$MEMORY_POOLBAMS" ] || [ -z "$WALLTIME_POOLBAMS" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi

        $QSUB $ARMED $NGSANE_WAITFORJOB -d -r -k $CONFIG -t $TASK_POOLBAMS -i $INPUT_POOLBAMS -e $ASD.bam -n $NODES_POOLBAMS \
    	    -c $CPU_POOLBAMS -m $MEMORY_POOLBAMS"G" -w $WALLTIME_POOLBAMS \
        	--postname postcommand${POOLED_DATA_NAME} \
    	    --postcommand "${NGSANE_BASE}/mods/poolBams.sh -k $CONFIG" 
 
    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then


        # start a new section for a mod
        NGSANE_REPORT_HEADER "Pool Bams" "$TASK_POOLBAMS" "poolBams.sh" "$ASD.bam"

        # add as many tables as needed. One table per result file
        NGSANE_REPORT_TABLE "$TASK_POOLBAMS" \
            "-" \
            "$OUT/<DIR>/$TASK_POOLBAMS"  \
            "$ASD.bam.stats" \
            "PATTERN!Total reads!! fgrep -w 'in total' | cut -d' ' -f 1" \
            "PATTERN!Secondary!! fgrep -w 'secondary' | cut -d' ' -f 1" \
            "PATTERN!Qfail!! fgrep -w 'in total' | cut -d' ' -f 3" \
            "PATTERN!Duplicates!! fgrep -w 'duplicates' | cut -d' ' -f 1" \
            "CALCULATE!%!40!#5*100/#2" \
            "PATTERN!Mapped!! fgrep -w 'mapped' | head -n 1 | cut -d' ' -f 1" \
            "CALCULATE!%!40!#7*100/#2" \
            "PATTERN!Mapped pairs!! fgrep -w 'properly paired' | cut -d' ' -f 1 | xargs echo 0.5* | bc " \
            "CALCULATE!%!40!#9*2*100/#2" \
            "PATTERN!Singletons!! fgrep -w 'singletons' | cut -d' ' -f 1" \
            "CALCULATE!%!40!#11*100/#2"
        
        # finish the section
        NGSANE_REPORT_FOOTER 
        
    fi
fi

