#!/bin/bash -e

################################################################################ 
#   recalibrate quality scores
#   http://www.broadinstitute.org/gsa/wiki/index.php/Base_quality_score_recalibration
#   http://www.broadinstitute.org/gsa/wiki/index.php/Local_realignment_around_indels
#   http://picard.sourceforge.net/command-line-overview.shtml#FixMateInformation
#   full pipe: http://www.broadinstitute.org/gsa/wiki/index.php/Whole_genome,_deep_coverage
# IN:$SOURCE/$dir/fastq/*$READONE.fastq
# OUT: $OUT/$dir/reCal/*$ASR.bam
################################################################################

if [ -n "$RUNRECALALN" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
    
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # check if resources are properly defined

        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_RECALALN -i $INPUT_RECALALN -e $ASD.bam \
            -n $NODES_RECALALN -c $CPU_RECALALN -m $MEMORY_RECALALN"G" -w $WALLTIME_RECALALN \
            --command "${NGSANE_BASE}/mods/reCalAln.sh -k $CONFIG -f <FILE> -r $FASTA -d $DBSNPVCF -o $OUT/<DIR>/$TASK_RECALALN"

    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then

        NGSANE_REPORT_HEADER "Recalibrate + Realign" "$TASK_RECALALN" "reCalAln.sh"

        NGSANE_REPORT_TABLE "$TASK_RECALALN" \
            "-" \
            "$OUT/<DIR>/$TASK_RECALALN"  \
            "$ASR.bam.stats" \
            "PATTERN!Total reads!! fgrep -w 'in total' | cut -d' ' -f 1" \
            "PATTERN!Secondary!! fgrep -w 'secondary' | cut -d' ' -f 1" \
            "PATTERN!Qfail!! fgrep -w 'in total' | cut -d' ' -f 3" \
            "PATTERN!Duplicates!! fgrep -w 'duplicates' | cut -d' ' -f 1" \
            "CALCULATE!%!40!#5*100/#2" \
            "PATTERN!Mapped!! fgrep -w 'mapped' | head -n 1 | cut -d' ' -f 1" \
            "CALCULATE!%!40!#7*100/#2" \
            "PATTERN!Mapped pairs!! fgrep -w 'properly paired' | cut -d' ' -f 1 | xargs echo 0.5* | bc " \
            "CALCULATE!%!40!#9*2*100/#2" \
            "PATTERN!Singletons!! fgrep -w 'singletons' | cut -d' ' -f 1" \
            "CALCULATE!%!40!#11*100/#2" \
#            "PATTERN!Imprparied!!sed -n 10p | cut -d' ' -f 1" \
#            "PATTERN!Imprregpaired!!sed -n 11p | cut -d' ' -f 1" \
#            TODO check last two entried

        NGSANE_REPORT_FOOTER 
        
    fi
fi	

	