#!/bin/bash -e

################################################################################
#   Mapping using Yara
#
# IN:$SOURCE/$dir/fastq/*read1.fastq
# OUT: $OUT/$dir/yara/*.bam
################################################################################

if [ -n "$RUNYARA" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
        
    ############################################################################
    # Wether to submit a job or compile a report
    if [ -z "$NGSANE_COMPILE_REPORT" ]; then

        # check if resources are properly defined
        if [ -z "$TASK_YARA" ] || [ -z "$NODES_YARA" ] || [ -z "$CPU_YARA" ] || [ -z "$MEMORY_YARA" ] || [ -z "$WALLTIME_YARA" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
        
        if [ ! -f ${FASTA%.*}.sa.val ];then
            # submit job for index generation if necessary
            INDEXJOBIDS=$(
                $QSUB $ARMED $NGSANE_WAITFORJOB -k $CONFIG -t $TASK_YARA -i $INPUT_YARA -e $READONE.$FASTQ \
                -n $NODES_YARA -c $CPU_YARA -m $MEMORY_YARA"G" \
                -w $WALLTIME_YARA --commontask indexGenome \
                --command "${NGSANE_BASE}/mods/yaraIndex.sh -k $CONFIG"
            ) && echo -e "$INDEXJOBIDS"
            INDEXJOBIDS=$(waitForJobIds "$INDEXJOBIDS")
        else
            INDEXJOBIDS=$NGSANE_WAITFORJOB
        fi
        
        $QSUB $ARMED -k $CONFIG -t $TASK_YARA -i $INPUT_YARA -e $READONE.$FASTQ \
            -n $NODES_YARA -c $CPU_YARA -m $MEMORY_YARA"G" -w $WALLTIME_YARA  $INDEXJOBIDS \
            --command "${NGSANE_BASE}/mods/yara.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_YARA --rgsi <DIR>"        
        
    ############################################################################
    # compile a report for this mod
    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then  

        NGSANE_REPORT_HEADER "Yara" "$TASK_YARA" "yara.sh" "$ASD.bam"

        NGSANE_REPORT_TABLE "$TASK_YARA" \
            "-" \
            "$OUT/<DIR>/$TASK_YARA"  \
            "$ASD.bam.stats" \
            "LINK!<SAMPLE>$ASD.bam.html" \
            "PATTERN!Total reads!! fgrep -w 'in total' | cut -d' ' -f 1" \
            "PATTERN!Secondary!! fgrep -w 'secondary' | cut -d' ' -f 1" \
            "PATTERN!Qfail!! fgrep -w 'in total' | cut -d' ' -f 3" \
            "PATTERN!Duplicates!! fgrep -w 'duplicates' | cut -d' ' -f 1" \
            "CALCULATE!%!40!#5*100/#2" \
            "PATTERN!Mapped!! fgrep -w 'mapped' | head -n 1 | cut -d' ' -f 1" \
            "CALCULATE!%!40!#7*100/#2" \
            "PATTERN!Mapped pairs!! fgrep -w 'properly paired' | cut -d' ' -f 1 | xargs echo 0.5* | bc " \
            "CALCULATE!%!40!#9*2*100/#2" \
            "PATTERN!Singletons!! fgrep -w 'singletons' | cut -d' ' -f 1" \
            "CALCULATE!%!40!#11*100/#2"

        
        NGSANE_REPORT_FOOTER 
        
    fi
fi